name = "MultiModalMuSig"
uuid = "a66acb62-5df1-561a-8400-71bc98699397"
version = "0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "0.17.1, 0.21.1, 1.1"
NLopt = "0.5.1, 0.6.0"
SpecialFunctions = "0.8.0, 0.10.3"
julia = "~0.7.0, ~1.0, ~1.1, ~1.2, ~1.3, ~1.4"
